"""Structural tests for the generated rhineland.rs.

Exercises the ADR-0012 codegen end-to-end against the real contract and
asserts the emitted Rust has the expected shape:

- header stamps contract SHA, font version, timestamp
- every atom emits as ``pub const NAME: Glyph``
- codepoints emit as Rust ``char`` literals (``'\\u{NNNN}'``), NOT integers
  — must match Rhena's existing ``Glyph { codepoint: char }`` type
- compositional atoms emit a parallel ``CompositionalMetadata`` static
- ``ALL_GLYPHS`` and ``ALL_COMPOSITIONAL_META`` slices present

Structural rather than byte-exact — a byte-exact golden would be fragile
against intentional tweaks to comments/formatting. For reproducibility
under pinned inputs, see test_determinism.py.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path


def _run_generator(script: Path, contract: Path, out: Path) -> None:
    env = dict(os.environ, SOURCE_DATE_EPOCH="1776931200")  # 2026-04-20
    subprocess.run(
        [sys.executable, str(script), "--contract", str(contract), "--out", str(out)],
        check=True,
        env=env,
    )


def test_header_contains_provenance(
    contract_path: Path, scripts_dir: Path, tmp_path: Path
):
    out = tmp_path / "rhineland.rs"
    _run_generator(scripts_dir / "generate-rhena-glyphs.py", contract_path, out)
    text = out.read_text(encoding="utf-8")

    assert text.startswith("//! @generated by hildegard-neumes")
    assert "sha256:" in text
    assert "Font version:" in text
    assert "ADR-0012" in text


def test_every_contract_atom_emits_a_glyph_const(
    contract_path: Path, scripts_dir: Path, tmp_path: Path
):
    out = tmp_path / "rhineland.rs"
    _run_generator(scripts_dir / "generate-rhena-glyphs.py", contract_path, out)
    text = out.read_text(encoding="utf-8")

    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    for g in contract["glyphs"]:
        const_decl = f"pub const {g['rust_const']}: Glyph = Glyph {{"
        assert const_decl in text, f"missing glyph const: {g['rust_const']}"


def test_codepoints_emit_as_char_literals(
    contract_path: Path, scripts_dir: Path, tmp_path: Path
):
    """Rhena's Glyph.codepoint is typed `char`; int literals would fail."""
    out = tmp_path / "rhineland.rs"
    _run_generator(scripts_dir / "generate-rhena-glyphs.py", contract_path, out)
    text = out.read_text(encoding="utf-8")

    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    for g in contract["glyphs"]:
        hex_digits = g["smufl_codepoint"].removeprefix("U+").upper()
        char_literal = f"'\\u{{{hex_digits}}}'"
        assert char_literal in text, (
            f"{g['rust_const']}: expected char literal {char_literal} not found"
        )

    # And explicitly assert there are no bare integer codepoint literals
    # (e.g. `0xE990`) being passed to a char field.
    assert not re.search(r"codepoint:\s*0x[0-9A-F]+", text), (
        "found integer-literal codepoint; must emit char literals"
    )


def test_compositional_atoms_emit_metadata_statics(
    contract_path: Path, scripts_dir: Path, tmp_path: Path
):
    out = tmp_path / "rhineland.rs"
    _run_generator(scripts_dir / "generate-rhena-glyphs.py", contract_path, out)
    text = out.read_text(encoding="utf-8")

    contract = json.loads(contract_path.read_text(encoding="utf-8"))
    compositional = [g for g in contract["glyphs"] if g.get("compose_anchors")]
    for g in compositional:
        meta_decl = (
            f"pub static {g['rust_const']}_META: CompositionalMetadata ="
        )
        assert meta_decl in text, (
            f"missing compositional metadata: {g['rust_const']}_META"
        )

    # And non-compositional atoms must NOT have a _META.
    non_comp = [g for g in contract["glyphs"] if not g.get("compose_anchors")]
    for g in non_comp:
        assert f"{g['rust_const']}_META" not in text, (
            f"non-compositional atom {g['rust_const']} should not emit _META"
        )


def test_compose_anchors_use_empty_spread(
    contract_path: Path, scripts_dir: Path, tmp_path: Path
):
    """Rhena expects `..ComposeAnchors::EMPTY` spread — EMPTY lives
    hand-written on their side, generator just references it."""
    out = tmp_path / "rhineland.rs"
    _run_generator(scripts_dir / "generate-rhena-glyphs.py", contract_path, out)
    text = out.read_text(encoding="utf-8")

    assert "..ComposeAnchors::EMPTY" in text
    # And the generator must NOT emit a definition of EMPTY.
    assert "const EMPTY:" not in text, (
        "generator emitted ComposeAnchors::EMPTY definition; it must "
        "live hand-written on the Rhena side"
    )


def test_all_glyphs_and_all_compositional_meta_slices_present(
    contract_path: Path, scripts_dir: Path, tmp_path: Path
):
    out = tmp_path / "rhineland.rs"
    _run_generator(scripts_dir / "generate-rhena-glyphs.py", contract_path, out)
    text = out.read_text(encoding="utf-8")

    assert re.search(r"pub const ALL_GLYPHS:\s*&\[&Glyph\]\s*=\s*&\[", text)
    assert re.search(
        r"pub const ALL_COMPOSITIONAL_META:\s*&\[&CompositionalMetadata\]\s*=\s*&\[",
        text,
    )
