#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""generate-rhena-glyphs.py — emit rhineland.rs for Rhena/Viriditas.

Per Rhena ADR-0012, chant glyph delivery shifted from inline path data to
@font-face + codepoint. The Rhena-facing artifact is now the WOFF file
itself, and this script emits a compact Rust table of per-glyph metadata
sourced directly from the authoritative contract at
docs/rhena-coordination/rhineland.contract.json.

Emission shape (per Rhena v2 feedback): two parallel tables rather than
one wide struct, so Rhena's existing chant.rs entries (which don't need
compositional data) stay untouched.

  * ``Glyph { name, codepoint }`` — one per contract glyph (all 25).
  * ``CompositionalMetadata { name, compose_anchors, stem_channel }`` —
    only for atoms that participate in compound-neume composition
    (the pes + flexa families; 8 atoms currently).

No OTF path extraction — the font IS the deliverable; this script just
provides codepoint + layout metadata. The @generated header stamps the
contract SHA-256, font version, and UTC timestamp.

Usage:
    python scripts/generate-rhena-glyphs.py \\
        --contract docs/rhena-coordination/rhineland.contract.json \\
        --out generated/rhineland.rs
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path


ANCHOR_FIELDS = ("pitch_top", "pitch_bottom", "stem_top", "stem_bottom", "base", "tip")


def _timestamp() -> str:
    """UTC timestamp in ISO-8601, honoring SOURCE_DATE_EPOCH for reproducible builds."""
    epoch_str = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch_str:
        dt = datetime.fromtimestamp(int(epoch_str), timezone.utc)
    else:
        dt = datetime.now(timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def rust_header(contract_path: Path, contract_bytes: bytes, version: str) -> str:
    sha = hashlib.sha256(contract_bytes).hexdigest()
    ts = _timestamp()
    return (
        "//! @generated by hildegard-neumes/scripts/generate-rhena-glyphs.py "
        f"at {ts}\n"
        f"//! Source contract: {contract_path.name} (sha256: {sha})\n"
        f"//! Font version: {version}\n"
        "//! Do not edit by hand — regenerate via "
        "`python scripts/generate-rhena-glyphs.py`.\n"
        "//!\n"
        "//! Rhineland glyph metadata for Rhena's @font-face + <text> chant\n"
        "//! renderer. Path data lives in the font file (WOFF); this module\n"
        "//! supplies codepoints and compositional anchor metadata per\n"
        "//! ADR-0012.\n"
        "//!\n"
        "//! Two parallel tables:\n"
        "//!   * ALL_GLYPHS — every atom as { name, codepoint } for @font-face\n"
        "//!     rendering.\n"
        "//!   * ALL_COMPOSITIONAL_META — only the pes/flexa family atoms\n"
        "//!     that participate in compound-neume composition, carrying\n"
        "//!     pitch/joint anchors and stem-channel x-bands.\n"
        "\n"
        "#![allow(clippy::unreadable_literal)]\n"
        "\n"
        "use super::{Glyph, Anchor, ComposeAnchors, StemChannel, "
        "CompositionalMetadata};\n"
        "\n"
    )


def codepoint_literal(cp: str | None) -> str:
    """Emit a Rust `char` literal (e.g. '\\u{E990}') from a "U+NNNN" codepoint.

    Rhena's Glyph type is `pub codepoint: char` (per ADR-0012); integer
    literals like 0xE990 would fail type-check against a char field since
    Rust doesn't auto-coerce int → char. Match the existing chant.rs style.
    """
    if cp is None:
        raise ValueError("every contract glyph must have a codepoint post-ADR-0012")
    hex_digits = cp.removeprefix("U+").upper()
    return "'\\u{" + hex_digits + "}'"


def short_doc(doc: str) -> str:
    # First sentence only, stripped of trailing period.
    return doc.split(". ")[0].rstrip(".")


def fmt_anchor(a: dict) -> str:
    return f"Some(Anchor {{ x: {a['x']}, y: {a['y']} }})"


def fmt_compose_anchors(ca: dict) -> str:
    """Emit only the non-None anchor fields, using ComposeAnchors::EMPTY
    spread for the unset fields (Rhena's preferred style)."""
    present = [(name, ca[name]) for name in ANCHOR_FIELDS if ca.get(name)]
    if not present:
        return "ComposeAnchors::EMPTY"
    fields = ", ".join(f"{name}: {fmt_anchor(val)}" for name, val in present)
    return f"ComposeAnchors {{ {fields}, ..ComposeAnchors::EMPTY }}"


def fmt_stem_channel(sc: dict | None) -> str:
    if not sc:
        return "None"
    return f"Some(StemChannel {{ x_min: {sc['x_min']}, x_max: {sc['x_max']} }})"


def emit_glyph(g: dict) -> str:
    return (
        f"/// {short_doc(g['doc'])}.\n"
        f"pub const {g['rust_const']}: Glyph = Glyph {{\n"
        f"    name: \"{g['font_name']}\",\n"
        f"    codepoint: {codepoint_literal(g['smufl_codepoint'])},\n"
        "};\n"
    )


def emit_compositional_meta(g: dict) -> str:
    return (
        f"pub static {g['rust_const']}_META: CompositionalMetadata = "
        "CompositionalMetadata {\n"
        f"    name: \"{g['font_name']}\",\n"
        f"    compose_anchors: {fmt_compose_anchors(g['compose_anchors'])},\n"
        f"    stem_channel: {fmt_stem_channel(g.get('stem_channel'))},\n"
        "};\n"
    )


def emit_all_glyphs(glyphs: list[dict]) -> str:
    names = ", ".join(f"&{g['rust_const']}" for g in glyphs)
    return (
        f"\n/// All {len(glyphs)} Rhineland glyphs in contract order.\n"
        f"pub const ALL_GLYPHS: &[&Glyph] = &[{names}];\n"
    )


def emit_all_compositional_meta(compositional: list[dict]) -> str:
    refs = ", ".join(f"&{g['rust_const']}_META" for g in compositional)
    return (
        f"\n/// All {len(compositional)} atoms carrying compositional "
        "metadata (pes + flexa families).\n"
        f"pub const ALL_COMPOSITIONAL_META: &[&CompositionalMetadata] = "
        f"&[{refs}];\n"
    )


def main(argv: list[str] | None = None) -> int:
    project_root = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--contract", type=Path,
        default=project_root / "docs" / "rhena-coordination" / "rhineland.contract.json",
    )
    parser.add_argument(
        "--out", type=Path,
        default=project_root / "generated" / "rhineland.rs",
    )
    parser.add_argument(
        "--version-file", type=Path,
        default=project_root / "VERSION",
    )
    args = parser.parse_args(argv)

    if not args.contract.is_file():
        sys.stderr.write(f"error: contract not found: {args.contract}\n")
        return 2

    contract_bytes = args.contract.read_bytes()
    contract = json.loads(contract_bytes)
    version = (
        args.version_file.read_text(encoding="utf-8").strip()
        if args.version_file.is_file() else "0.0.0-dev"
    )

    compositional = [g for g in contract["glyphs"] if g.get("compose_anchors")]

    parts = [rust_header(args.contract, contract_bytes, version)]
    for g in contract["glyphs"]:
        parts.append(emit_glyph(g))
    parts.append(emit_all_glyphs(contract["glyphs"]))
    parts.append("\n")
    for g in compositional:
        parts.append(emit_compositional_meta(g))
    parts.append(emit_all_compositional_meta(compositional))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(parts), encoding="utf-8")
    print(
        f"Emitted {len(contract['glyphs'])} glyphs "
        f"({len(compositional)} with compositional metadata) to {args.out}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
